In [1]:
import numpy as np

print(np.__version__)

2.5.1


In [2]:
!uv pip list | grep numpy

numpy                   2.5.1


In [3]:
import time

py_list =list(range(1000000))

start_time = time.time()

result_list = [x * 2 for x in py_list]

print(f"파이썬 리스트 연산 시간: {time.time() - start_time:.5f}초")

파이썬 리스트 연산 시간: 0.05956초


In [4]:
np.arange(10)

%time sum(range(1000000))

CPU times: user 15.4 ms, sys: 716 μs, total: 16.1 ms
Wall time: 88.3 ms


499999500000

In [5]:
import numpy as np

# 1,000만 개의 원소를 가진 NumPy 배열 생성
np_array = np.arange(10000000)

# 연산 시간 측정시작
start_time = time.time()

# 반복문 없이 배열 전체에 바로 2를 곱하는 벡터화 연산
result_array = np_array * 2

print(f"NumPy 배열 소요 시간: {time.time() - start_time:.4f} 초")


NumPy 배열 소요 시간: 0.0437 초


In [6]:
np.arange(10)  # ([start,] stop [,step])
# numpy을 이용한 계산
%time np.sum(np.arange(1000000))

CPU times: user 1.49 ms, sys: 2.33 ms, total: 3.82 ms
Wall time: 8.71 ms


np.int64(499999500000)

In [7]:
arr = np.array([[1,2,3], [4,5,6]])

print("배열의 차원: ", arr.ndim, np.ndim(arr))
print("배열의 형태 : ", arr.shape, np.shape(arr))
print("원소 총 개수 : ", arr.size, np.size(arr))

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입 : ", float_arr.dtype)

배열의 차원:  2 2
배열의 형태 :  (2, 3) (2, 3)
원소 총 개수 :  6 6
변경된 타입 :  float64


In [8]:
a = np.array([1,2,3])

print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [9]:
int64_a = np.array([1,2,3])
print(int64_a.dtype)

float32_b = int64_a.astype(np.float32)
print(float32_b)
print(float32_b.dtype)

int64
[1. 2. 3.]
float32


In [10]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # (3,)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [11]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [12]:
# 3차원 배열 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 2층(공간, 면), 2행 , 2열
print(c)          # [[[1,2][3,4]]  [[5,6][7,8]]]
print(dir(c))
print(type(c))     # <class 'numpy.ndarray'>
print(c.shape)     # (2, 2, 2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__

In [13]:
a = np.zeros(3)

print(a)

[0. 0. 0.]


In [14]:
a = np.zeros((2,3))

print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
a = np.ones(3)

print(a)

[1. 1. 1.]


In [16]:
a = np.ones((2,3))

print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
a = np.eye(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a = np.eye(3, 2)

print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [19]:
a = np.eye(3, 4, k=1)

print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### identity(x)
- 수학에서 단위행렬은 영어로 identity matrix
- 크기 한 개만 지정해서 생성할 수 있다.

In [20]:
a = np.identity(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.full((행, 열), 값)
- 지정한 크기의 배열을 생성하고 채울 값을 지정한다.


In [21]:
a = np.full((2,2), 1)

print(a)

[[1 1]
 [1 1]]


In [22]:
a = np.full((2,2), [1, 2])

print(a)

[[1 2]
 [1 2]]


In [23]:
a = np.full((2,2), [[1], [2]])

print(a)

[[1 1]
 [2 2]]


In [24]:
a = np.full((2,2), [[1,2], [3,4]])

print(a)

[[1 2]
 [3 4]]


### np.empty((행, 열))
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [25]:
a = np.empty(3)

print(a)

[1. 1. 1.]


In [26]:
a = np.empty((2,3))

print(a)

[[1. 0. 0.]
 [1. 0. 0.]]


### linspace
- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개가 생성된다면 세 번째 num인자 값이 생략되어 있으므로 start와 end 계산해서 default 50이 생성된다
- linspace(start, end, num)
- linspace(0, 49) #num의 default value 50

In [27]:
a = np.linspace(0, 49)

print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [28]:
a - np.linspace(0, 5)

print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [29]:
a = np.linspace(0, 5, endpoint=False)

print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


### logspace
- linspace과 비슷하다.
- log scale을 사용하는 차이가 있다.
- 1부터 50까지 사이의 10개의 요소를 생성한다.

In [30]:
a = np.logspace(1, 50)

print(a)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10
 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15 1.e+16 1.e+17 1.e+18 1.e+19 1.e+20
 1.e+21 1.e+22 1.e+23 1.e+24 1.e+25 1.e+26 1.e+27 1.e+28 1.e+29 1.e+30
 1.e+31 1.e+32 1.e+33 1.e+34 1.e+35 1.e+36 1.e+37 1.e+38 1.e+39 1.e+40
 1.e+41 1.e+42 1.e+43 1.e+44 1.e+45 1.e+46 1.e+47 1.e+48 1.e+49 1.e+50]


In [31]:
a = np.logspace(1, 50, 10)

print(a)

[1.00000000e+01 2.78255940e+06 7.74263683e+11 2.15443469e+17
 5.99484250e+22 1.66810054e+28 4.64158883e+33 1.29154967e+39
 3.59381366e+44 1.00000000e+50]


### arange
- np.arage(start, stop, step, dtype=Noe)
- start: 생성할 배열의 시작 값(기본값은 0)
- stop: 생성할 배열의 종료 값(이 값은 포함되지 않은)
- step: 숫자 사이의 간격(기본값은 1)
- dtype: 생성할 배열의 데이터 타입(옵션)

In [32]:
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
# 시작 값과 종료 값 설정
arr = np.arange(3, 10)  # 3부터 9까지
print(arr)              # [3 4 5 6 7 8 9]

[3 4 5 6 7 8 9]


In [34]:
# 간격 설정
arr = np.arange(1, 10, 2)  # 1부터 9까지 2씩 증가
print(arr)                 # [1 3 5 7 9]

[1 3 5 7 9]


In [35]:
# 실수 간격 사용
arr = np.arange(0, 1, 0.1)  # 0부터 1까지 0.1씩 증가
print(arr)  # [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### _like
- _like가 붙으면 shape이 같게 만들어진다
- 연산하기 위해서 shape을 맞춰야 하는 경우가 있다

In [36]:
a = np.array([[1,2,3], [4,5,6]])

print(a)

b = np.ones_like(a)

print(b)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


In [37]:
a = np.array([[1., 2.,3.], [4., 5., 6.]])

print(a)

b = np.zeros_like(a)

print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 난수(Random) 생성과 분포 빌드
- np.random.rand(행,열): 0 이상 1 미만의 구간에서 정해진 형태의 난수를 균등하게 추출하여 배열 빌드
- np.random.randn(행,열): 평균이 0이고 표준편차가 1인 표준정규분포(Standard Normal Distribution) 곡선에서 무작위 난수 배열 추출
- np.random.randint(low, high, size): 지정된 범위 (low 이상 high 미만) 안에서 무작위 정수형 난수 배열 생성
- 난수 발생 엔진에 특정 난수 초기값(Seed)을 부여하고 코드를 다시 실행해도 언제나 동일한 가상 데이터가 생성되도록 고정

In [38]:
np.random.seed(42)

num = np.random.rand(2, 3)

print(num)

normal_dist_matrix = np.random.randn(3, 3)

print(normal_dist_matrix)

lotto_numbers = np.random.randint(1, 45, size=6)
print(lotto_numbers)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]
[42 28 16 15 44  3]


### python, numpy 도움말

In [39]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [40]:
help(np.array)

Help on built-in function array in module numpy:

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or i

### python에서 copy

In [41]:
a = [1, 2, 3]        # list
b = a
print(b)
print(a is b )        # 메모리 주소 비교 True
b[0] = 7
print(a)               # [7, 2, 3]
print(b)                # [7, 2, 3]

[1, 2, 3]
True
[7, 2, 3]
[7, 2, 3]


In [42]:
# 1차원 list의 copy

a = [1,2,3]
b = a.copy()

id(a)
id(b)

print(a is b)
print(a == b)

b[0] = 8

print(a)
print(b)

print(a is b)
print(a == b)

False
True
[1, 2, 3]
[8, 2, 3]
False
False


In [43]:
# 2차원 list의 copy

a = [[1,2,3]]

print(type(a))

b = a.copy()

print(id(a))
print(id(b))

print(a is b)
print(a == b)

b[0][0] = 10

print(a[0])
print(b[0])

<class 'list'>
4604990976
4604990720
False
True
[10, 2, 3]
[10, 2, 3]


In [44]:
import copy

a = [[1,2,3]]
b = copy.deepcopy(a)

print(a[0] is b[0])
print(a[0] == b[0])

b[0][0] = 10

print(a[0] is b[0])
print(a[0] == b[0])

print(a)
print(b)

False
True
False
False
[[1, 2, 3]]
[[10, 2, 3]]


In [45]:
# [:]는 전체라는 뜻
# 슬라이싱 방식으로 1차원 리스트일 때는 재할당하면 deep copy가 된다
# 슬라이싱 방식으롤 2차원 리스트 이상인 경우는 shallow copy가 발생한다

a = [1,2,3]
b = a[:]

print(a)
print(b)

b[0] = 10
print(a)
print(b)

a = [[1,2,3]]
b = a[:]
print(a is b)
print(a == b)

print(a[0][0] is b[0][0])
print(a[0][0] == b[0][0])

[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[10, 2, 3]
False
True
True
True


In [46]:
# numpy의 copy

a = b = np.array([1,2,3])

print(a is b)
print(a == b)

a[0] = 100
print(a[0])
print(b[0])

a = np.array([1,2,3])
b = a.copy()

print(a is b)
print(a == b)

True
[ True  True  True]
100
100
False
[ True  True  True]


In [47]:
# 1차원 데이터 인덱싱
# 파이썬 리스트 구조와 동일하게 0번 인덱스부터 시작, 대괄호안에 주소 번호를 대입하여 원소추출
# 음수 값 인덱싱 제공을 통해 배열의 마지막 위치부터 역순으로 추적하여 접근 가능

numbers = np.array([1,3,5,7,9])

print(numbers[-1])

print(numbers[-2])

9
7


In [48]:
# 2차원 매트릭스 인덱싱([행, 열])
# 리스트의 중첩구조(arr[][])와 달리 numpy에서는 단일 대괄호 내부에 쉼표 하나로 행과 열을 동시에 제어 (arr[행, 열])
# 0번째 축(axis=0)과 1번째 축(axis=1)의 인덱스가 각각 독립적이고 유기적으로 결합되어 작동

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

target_value = arr[1,2]
print(target_value)

6


In [49]:
# 붉리언 인덱싱(Boolean Indexing)
# 조건 필터링 (예: 특정 값 이상인 데이터만 골라내기)
# 배열의 각 원소에 조건식(예: arr > 5)을 적용하여 참(True)과 거짓(False)으로 구성된 조건 배열 생성
# 생성된 Boolean 배열을 기존 배열의 인덱스로 주입하여 True인 위치의 값만 필터링하여 반환

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

bool_mask = arr > 5
print("bool_mask : ", bool_mask)
print(arr[bool_mask])
print(arr[arr > 5])

bool_mask :  [[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[6 7 8 9]


In [50]:
arr = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

axis_ABC = np.array(['A', 'A', 'B'])

bool_mask = axis_ABC == 'A'

print(bool_mask)
print(arr[bool_mask])

[ True  True False]
[[0 1 2 3]
 [4 5 6 7]]


In [51]:
# 팬시 인덱싱 (Fancy Indexing)
# 특정 인덱스 배열을 전달하여 비연속적인 데이터 추출하기
# 정수형 레이블이나 인덱스 번호가 담긴 리스트/배열을 전달하여 원하는 위치의 데이터를 한 번에 추출
# 연속적이지 않고 무작위로 떨어져 있는 특정 행이나 열을 임의로 골라낼 때 유용하게 활용

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[[0, 2]])

[[1 2 3]
 [7 8 9]]


In [52]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14]
])

print(arr[[1, 2]])     # [[3, 4,5], [6, 7, 8]]

print(arr[[-1, -2]])    # [[12, 13, 14], [9, 10, 11]]

[[3 4 5]
 [6 7 8]]
[[12 13 14]
 [ 9 10 11]]


In [53]:
# 팬시 인덱싱과 불리언 차이
# indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.

a = np.arange(24).reshape(2,3,4)

print(a)

print(a[0])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [54]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원을 2차원으로 가져온다.)
a[0]


# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
# fancy indexing은 원래 3차원 그대로 가져온다.
a[[0]]

# array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [56]:
# ellipsis
# …(ellipsis)은 이후의 모든 것을 의미한다.

# a[0]=a[0, :, :]=a[0,...]
print(a[0])  # indexing 기법
print(a[0, :, :]) # slicing 기법
print(a[0,...])  # ellipsis 기법(생략기법)


# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
type(...)

ellipsis

In [58]:
a[[0], :, :] # b[[0]]은  b[[0], :, :]의 단축 표현이다.

# array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]]])


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [59]:
a[0, :, 1]        # array([1, 5, 9])

array([1, 5, 9])

In [60]:
a[[0],:, [1]]     # array([[1, 5, 9]])

array([[1, 5, 9]])

In [61]:
# 숫자 1, 5, 9, 3, 7, 11가져오기
print(a[0, :, 1])              # [1 5 9]

[1 5 9]


In [62]:
a[[0], :, [1]]                 # array([[1, 5, 9]])

array([[1, 5, 9]])

In [63]:
# 숫자 1,5,9,3,7,11 가져오기
a[[0], :, [1,3]]

# ```
# array([[ 1,  5,  9],
#        [ 3,  7, 11]])

#  ```

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [64]:
a[:, 1, :]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [65]:
a[:, [1], :]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [66]:
b = a[:, [1], :]
b.shape

(2, 1, 4)

In [67]:
a[:, :, [1]]

# ```
# array([[[ 4,  5,  6,  7]],

#        [[16, 17, 18, 19]]])
#  ```

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [68]:
a[:, :, -1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [69]:
# [
#     [
#         [ 0  1  2  3]
#         [ 4  5  6  7]
#         [ 8  9 10 11]
#     ]
#     [
#         [ 0  1  2  3]
#         [ 4  5  6  7]
#         [ 8  9 10 11]
#     ]
#     [
#         [ 0  1  2  3]
#         [ 4  5  6  7]
#         [ 8  9 10 11]
#     ]
# ]


In [70]:
# out에 나오는 ...은 단순히 줄임표현이다.
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [71]:
# ... 양쪽으로 출력 갯수 지정
np.set_printoptions(edgeitems=6)

np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999], shape=(10000,))

In [72]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}')


print(f'is 확인:: {arr is dap}')

[1 2 3 4]
메모리 공유 확인:: False
is 확인:: False


In [73]:
# 1차원 12개 원소 배열을 3행 4열 2차원 배열로 변경
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

print(arr_1d)
print(arr_2d)
# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d ,arr_2d)}')


# 행의 크기는 2로 지정하고, 열의 크기는 자동 계산(-1)하여 배치
arr_auto = arr_1d.reshape(2, -1)  # 결과적으로 2행 6열로 자동 변환됨

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d,arr_auto)}')

arr_2d = arr_1d.reshape(3, 4)
arr_line= np.ravel(arr_2d)

# [ 0  1  2  3  4  5  6  7  8  9 10 11]
print(arr_line)

#메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_2d, arr_line)}')



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
메모리 공유 확인:: True
메모리 공유 확인:: True
[ 0  1  2  3  4  5  6  7  8  9 10 11]
메모리 공유 확인:: True


In [74]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]

print(np.r_[a,b])                              # [[1 2 3][4 5 6]]

v_row = np.vstack([a,b])
print(f'v_row:: {v_row}')                      # v_row:: [[1 2 3][4 5 6]]

concat_row = np.concatenate((a, b), axis=0)    # axis = 0
print(f'concat_row:: {concat_row}')            # concat_row:: [[1 2 3][4 5 6]]

a=[[1 2 3]]
b=[[4 5 6]]
[[1 2 3]
 [4 5 6]]
v_row:: [[1 2 3]
 [4 5 6]]
concat_row:: [[1 2 3]
 [4 5 6]]


In [75]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]

print(np.c_[a,b])                              # [[1 2 3 4 5 6]]

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [[1 2 3 4 5 6]]

concat_col = np.concatenate((a, b), axis=1)    # axis = 1
print(f'concat_col:: {concat_col}')            # concat_col:: [[1 2 3 4 5 6]]

a=[[1 2 3]]
b=[[4 5 6]]
[[1 2 3 4 5 6]]
h_col:: [[1 2 3 4 5 6]]
concat_col:: [[1 2 3 4 5 6]]


In [76]:
a = np.array([1, 2, 3])
print(f'a={a}')           # a=[1 2 3]

b = np.array([4, 5, 6])
print(f'b={b}')           # b=[4 5 6]

print(np.r_[a,b])

h_row = np.vstack([a,b])
print(f'h_row:: {h_row}')     # h_row:: [[1 2 3][4 5 6]]

concat_row = np.concatenate((a, b), axis=0)  # axis = 0
print(f'concat_row:: {concat_row}') # concat_row:: [1 2 3 4 5 6]

a=[1 2 3]
b=[4 5 6]
[1 2 3 4 5 6]
h_row:: [[1 2 3]
 [4 5 6]]
concat_row:: [1 2 3 4 5 6]


In [77]:
a = np.array([1, 2, 3])
print(f'a={a}')                                # a=[1 2 3]

b = np.array([4, 5, 6])
print(f'b={b}')                                # b=[4 5 6]

print(np.c_[a,b])                              # [[1 4][2 5][3 6]]

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [1 2 3 4 5 6]

# AxisError: axis 1 is out of bounds for array of dimension 1
# concat_col = np.concatenate((a, b), axis=1)    # axis = 1

a=[1 2 3]
b=[4 5 6]
[[1 4]
 [2 5]
 [3 6]]
h_col:: [1 2 3 4 5 6]


In [78]:
a = np.arange(12).reshape(3,4)
print(a)
x, y = np.split(a, 2, axis = 1)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [79]:
# 2차원이면 3차원으로 증가한다.

print(b)

print("--------------------------------------------------------")
b = np.stack((x,y), axis = 0)
print(b.shape) # 2차원(m, n) => 3차원(2, m, n)
print("--------------------------------------------------------")
print(b)


[4 5 6]
--------------------------------------------------------
(2, 3, 2)
--------------------------------------------------------
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]


In [80]:
b = np.stack((x,y), axis = 1)
print(b.shape) # 2차원(m, n) => 3차원(m,2, n)
print("--------------------------------------------------------")
print(b)


(3, 2, 2)
--------------------------------------------------------
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [81]:
print(x)
print("--------------------------------------------------------")
print(y)
print("--------------------------------------------------------")
c = np.concatenate((x, y), axis=0)
print(c.shape)
print("--------------------------------------------------------")
print(c)

[[0 1]
 [4 5]
 [8 9]]
--------------------------------------------------------
[[ 2  3]
 [ 6  7]
 [10 11]]
--------------------------------------------------------
(6, 2)
--------------------------------------------------------
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]


In [82]:
print(x)
print("--------------------------------------------------------")
print(y)
print("--------------------------------------------------------")
c = np.concatenate((x, y), axis=1)
print(c.shape)
print("--------------------------------------------------------")
print(c)

[[0 1]
 [4 5]
 [8 9]]
--------------------------------------------------------
[[ 2  3]
 [ 6  7]
 [10 11]]
--------------------------------------------------------
(3, 4)
--------------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [83]:
x = np.arange(18)
print(f'x::{x}')
print("--------------------------------------------------------")
x = x.reshape(-1, 6)
print(f'x::{x}')
print("--------------------------------------------------------")
print(np.hsplit(x, 3))
print("--------------------------------------------------------")
print(np.hsplit(x, (2,4)))
print("--------------------------------------------------------")
print(np.split(x, 3, axis=1))
print("--------------------------------------------------------")
print(np.split(x, (2, 4), axis=1))

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
--------------------------------------------------------
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
--------------------------------------------------------
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
--------------------------------------------------------
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
--------------------------------------------------------
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
--------------------------------------------------------
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), ar

In [84]:
x = np.arange(18)
print(f'x::{x}')
print("--------------------------------------------------------")
x = x.reshape(-1, 6)
print(f'x::{x}')
print("--------------------------------------------------------")
print(np.vsplit(x, 3))
print(np.vsplit(x, (1,2)))

print(np.split(x, 3, axis=0))
print("--------------------------------------------------------")
print(np.split(x, (1, 2), axis=0))

# [array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
--------------------------------------------------------
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
--------------------------------------------------------
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
--------------------------------------------------------
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]


In [85]:
arr = np.array([1, 2, 3]) # shape: (3,)

# 행 방향(axis 0) 확장 -> shape: (1, 3)
row_vec = arr[np.newaxis, :]

# 열 방향(axis 1) 확장 -> shape: (3, 1)
col_vec = arr[:, np.newaxis]


print("--------------------------------------------------------")
print("행벡터:\n", row_vec)
print("--------------------------------------------------------")
print("열벡터:\n", col_vec)

--------------------------------------------------------
행벡터:
 [[1 2 3]]
--------------------------------------------------------
열벡터:
 [[1]
 [2]
 [3]]


In [86]:
print( np.newaxis is None)
print("--------------------------------------------------------")
# 열 추가

a = np.arange(12).reshape(3,4)
print(a)
print("--------------------------------------------------------")

b = a[ :, :, None ]
print(b.shape) # (3, 4, 1)
print("--------------------------------------------------------")
print(b)
print("--------------------------------------------------------")

True
--------------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------------
(3, 4, 1)
--------------------------------------------------------
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
--------------------------------------------------------


In [87]:
import numpy as np

arr = np.array([1, 2, 3]) # shape: (3,)

# axis=0 위치에 차원 추가 -> shape: (1, 3)
e0 = np.expand_dims(arr, axis=0)
print('e0: ', e0)
print("--------------------------------------------------------")
# axis=1 위치에 차원 추가 -> shape: (3, 1)
e1 = np.expand_dims(arr, axis=1)
print("e1 : ", e1)
print("--------------------------------------------------------")
print("e0.shape:", e0.shape) # (1, 3)
print("--------------------------------------------------------")
print("e1.shape:", e1.shape) # (3, 1)

e0:  [[1 2 3]]
--------------------------------------------------------
e1 :  [[1]
 [2]
 [3]]
--------------------------------------------------------
e0.shape: (1, 3)
--------------------------------------------------------
e1.shape: (3, 1)


In [88]:
import numpy as np

# shape: (1, 3, 1) 인 3차원 배열
arr_3d = np.array([[[1], [2], [3]]])

# 크기가 1인 모든 차원 축소 -> shape: (3,)
squeezed = np.squeeze(arr_3d)

print("원래 shape:", arr_3d.shape) # (1, 3, 1)
print("--------------------------------------------------------")
print("축소 후 shape:", squeezed.shape) # (3,)
print("--------------------------------------------------------")
print("결과:", squeezed) # [1 2 3]

원래 shape: (1, 3, 1)
--------------------------------------------------------
축소 후 shape: (3,)
--------------------------------------------------------
결과: [1 2 3]


In [89]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]]) # shape: (2, 2)

# 모두 1차원 배열 [1, 2, 3, 4] (shape: (4,))로 변환
r_arr = matrix.ravel()
f_arr = matrix.flatten()
re_arr = matrix.reshape(-1)

print("1차원 평탄화 결과:", r_arr) # [1 2 3 4]

1차원 평탄화 결과: [1 2 3 4]


In [90]:
a = np.arange(24).reshape(2,3,4)

# print(a)

# [
#     [
#         [0,1,2,3],
#         [4,5,6,7],
#         [8,9,10,11],
#     ],
#     [
#         [0,1,2,3],
#         [4,5,6,7],
#         [8,9,10,11],
#     ]
# ]

print(a[[0],:,[1]])
print(a[[0],[1],:])
# result = a[0, :, :]
# print(result.shape)

[[1 5 9]]
[[4 5 6 7]]


In [91]:
import numpy as np

# 1. 벡터 및 행렬 생성
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# 2. 벡터 내적 (Dot Product)
dot_product = np.dot(v1, v2)
print("Vector Dot Product:")
print(dot_product)
# 출력: 32 (1*4 + 2*5 + 3*6)

# 3. 행렬 곱셈 (Matrix Multiplication)
matrix_mul = np.matmul(A, B) # 또는 A @ B
print("\nMatrix Multiplication (A @ B):")
print(matrix_mul)
# 출력:
# [[19 22]
#  [43 50]]

# 4. 전치 행렬 (Transpose Matrix)
A_transpose = A.T
print("\nTranspose of Matrix A:")
print(A_transpose)
# 출력:
# [[1 3]
#  [2 4]]

# 5. 역행렬 (Inverse Matrix)
A_inv = np.linalg.inv(A)
print("\nInverse of Matrix A:")
print(A_inv)
# 출력:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 6. 행렬식 (Determinant)
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:")
print(det_A)
# 출력: -2.0 (1*4 - 2*3)

# 7. 고유값 및 고유벡터 (Eigenvalues & Eigenvectors)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigenvalues)
# 출력: [-0.37228132  5.37228132]

print("\nEigenvectors of A:")
print(eigenvectors)
# 출력:
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]

Vector Dot Product:
32

Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of Matrix A:
-2.0000000000000004

Eigenvalues of A:
[-0.37228132+0.j  5.37228132+0.j]

Eigenvectors of A:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


In [92]:
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]

def matrix_calculator(a, b):
    result = []

    for i in range(len(a)):
        matrix_list = []

        for j in range(len(b[0])):
            temp = 0

            for k in range(len(b)):
                temp += a[i][k] * b[k][j]

            matrix_list.append(temp)

        result.append(matrix_list)

    return result

print(matrix_calculator(a, b))

[[19, 22], [43, 50]]


In [93]:
import numpy as np

# 1. shape (3, 5) 크기의 2차원 배열 생성
a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

# 2. 전치(Transpose) 및 축 교환(Swap Axes) 연산 (모두 동일한 결과 반환)
# ① .T 속성 사용
transposed_T = a.T

# ② np.transpose() 함수 사용
transposed_func = np.transpose(a)

# ③ np.swapaxes() 함수 사용 (0번 축과 1번 축을 맞바꿈)
swapped = np.swapaxes(a, 0, 1)

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(a)
# 원본 배열 출력 (shape: 3, 5):
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]]

# ① a.T -> 전치 행렬
print(transposed_T)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# ② np.transpose(a) -> 전치 행렬
print(transposed_func)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# ③ np.swapaxes(a, 0, 1) -> 축 맞바꿈
print(swapped)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# Shape(모양) 확인 ( (3, 5) -> (5, 3)으로 변환 )
print(a.shape)            # 원본 크기 -> 출력: (3, 5)
print(transposed_T.shape) # 변환 후 크기 -> 출력: (5, 3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(3, 5)
(5, 3)


In [94]:
b = np.matrix([[1,2], [3,4]]) # 행렬 생성  [[1 2][3 4]]
print(b)

print(type(b))            # numpy.matrix

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [95]:
b * b
#  1*1 + 2*3=7    1*2+2*4=10
#  3*1 + 4*3=15   3*2+4*4=22

# [[1*1+2*3   1*2+2*4]      [[7,10]
#  [3*1+4*3   3*2+4*4]]      [15,22]]

# (2,2)  (2,2)  # 앞의 행과 뒤의 열의 갯수가 같아야 한다.


matrix([[ 7, 10],
        [15, 22]])

In [96]:
c = np.matrix([[1,2], [3,4]]) # 행렬 생성
print(c)

print(c)
print(c.shape)

print(c * c.T)
# print(c * np.dot(c.T)) # 함수방법으로 np.dot( )함수를 사용할 수 있다.
print( c.dot(c.T) ) # 메소드(method) 방식
print(c @ c.T)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
(2, 2)
[[ 5 11]
 [11 25]]
[[ 5 11]
 [11 25]]
[[ 5 11]
 [11 25]]


In [97]:
import numpy as np

# 1. 시드 고정 및 가상의 학생 성적 데이터셋 생성 (학생 5명, 과목 3개)
np.random.seed(42)
scores = np.random.randint(40, 101, size=(5, 3))

print("1. 원본 성적 데이터셋 (5명 x 3과목):")
print(scores)

# 2. 각 과목별 평균 및 표준편차 구하기 (axis=0: 세로/열 방향 연산)
subject_mean = np.mean(scores, axis=0)
subject_std = np.std(scores, axis=0)

print("\n2. 과목별 평균:")
print(subject_mean)

print("\n3. 과목별 표준편차:")
print(np.round(subject_std, 2))

# 3. 각 학생별 평균 구하기 (axis=1: 가로/행 방향 연산)
student_mean = np.mean(scores, axis=1)

print("\n4. 학생별 평균 점수:")
print(np.round(student_mean, 2))

# 4. 낙제점 수정하기 (60점 미만인 점수를 60점으로 일괄 수정)
# np.where(조건, 참일 때 값, 거짓일 때 값) 활용
fixed_scores = np.where(scores < 60, 60, scores)

print("\n5. 낙제점(60점 미만) 수정 후 데이터셋:")
print(fixed_scores)

1. 원본 성적 데이터셋 (5명 x 3과목):
[[ 78  91  68]
 [ 54  82  47]
 [100  60  78]
 [ 97  58  62]
 [ 50  50  63]]

2. 과목별 평균:
[75.8 68.2 63.6]

3. 과목별 표준편차:
[20.88 15.57 10.05]

4. 학생별 평균 점수:
[79.   61.   79.33 72.33 54.33]

5. 낙제점(60점 미만) 수정 후 데이터셋:
[[ 78  91  68]
 [ 60  82  60]
 [100  60  78]
 [ 97  60  62]
 [ 60  60  63]]


In [98]:
import numpy as np

# 1. 가상의 RGB 이미지 픽셀 데이터 생성 (높이 4 x 너비 4 x 채널 3)
np.random.seed(100)
image_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)

print("1. 원본 RGB 이미지 Shape:")
print(image_rgb.shape)

# 2. RGB 흑백 전환 (Grayscale Conversion)
# ITU-R BT.601 표준 공식: Y = 0.299*R + 0.587*G + 0.114*B
# 채널 축(axis 2)에 가중치를 내적(Dot Product)하거나 브로드캐스팅하여 계산함
weights = np.array([0.299, 0.587, 0.114])
image_gray = np.dot(image_rgb, weights).astype(np.uint8)

print("\n2. 흑백 전환 후 이미지 Shape:")
print(image_gray.shape)  # (4, 4)로 차원 축소됨

print("\n3. 흑백 이미지 픽셀 값:")
print(image_gray)

# 3. 이미지 크기 조절 (Downsampling / Resizing)
# 슬라이싱([::2, ::2])을 이용하여 가로/세로 픽셀을 2칸씩 스킵함으로써 크기를 1/2로 줄임
image_resized = image_gray[::2, ::2]

print("\n4. 크기 조절(2x2로 축소) 후 이미지 Shape:")
print(image_resized.shape)

print("\n5. 최종 축소된 이미지 픽셀 값:")
print(image_resized)

1. 원본 RGB 이미지 Shape:
(4, 4, 3)

2. 흑백 전환 후 이미지 Shape:
(4, 4)

3. 흑백 이미지 픽셀 값:
[[ 93  80 170  63]
 [175  87 124 128]
 [ 97 173  36  50]
 [ 89  73  33 139]]

4. 크기 조절(2x2로 축소) 후 이미지 Shape:
(2, 2)

5. 최종 축소된 이미지 픽셀 값:
[[ 93 170]
 [ 97  36]]
