In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

print(a)
print(type(a))
print(a.dtype)
print(a.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)


In [3]:
b = np.array([1.2, 3.1, 4])
print(b.dtype)
print(b[0])

float64
1.2


In [4]:
a = np.array([[1,2], [3,4]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2]
 [3 4]]
(2, 2)
2


In [5]:
print(np.zeros(5))
print(np.zeros_like(a))

print("-----------------")

print(np.ones(5))
print(np.ones_like(a))

print("-----------------")

print(np.zeros((3,3)))

print("-----------------")

print(np.arange(3, 10, 2))
print(np.arange(0, 1, 0.1))
print(np.linspace(0, 1, 10, endpoint=True))

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
-----------------
[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]
-----------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b

print(c)

[5 7 9]


In [7]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([[4,5,6], [1,1,1]])

c = a + b
d = a - b
print(c)
print(d)
print(a*b)
print(a/b)
print(b**2)

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]
[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [8]:
scores = np.array([
    [80, 90, 70],
    [60, 85, 75],
    [90, 95, 100],
    [70, 65, 80],
    [85, 75, 90]
])

In [9]:
# 학생별 총점 구하기


print(scores.sum(axis=1))

[240 220 285 215 250]


In [10]:
# 학생별 평균 구하기

print(scores.mean(axis=1))

[80.         73.33333333 95.         71.66666667 83.33333333]


In [11]:
# 과목별 평균 구하기

print(scores.mean(axis=0))

[77. 82. 83.]


In [12]:
# 평균이 80점 이상인 학생만 출력

print(scores[scores.mean(axis=1) >= 80])

[[ 80  90  70]
 [ 90  95 100]
 [ 85  75  90]]


In [13]:
sales = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [20, 30, 40, 50]
])

In [14]:
# 2번째 매장의 데이터 출력

print(sales[1])

[15 25 35 45]


In [15]:
# 3주차 판매량만 출력

print(sales[:,2])

[30 35 40]


In [16]:
# 전체 판매량 중 40 이상인 값만 출력

print(sales[sales >= 40])

[40 45 40 50]


In [17]:
# 평균보다 높은 판매량 찾기

print(sales[sales > np.mean(sales)])

[40 35 45 40 50]


In [18]:
stock = np.array([
    [
        [10,20,30],
        [15,25,35]
    ],
    [
        [20,30,40],
        [25,35,45]
    ]
])

In [19]:
# 첫 번째 상품 전체 출력

print(stock[0,0])

[10 20 30]


In [20]:
# 모든 상품의 2번째 월 재고 출력

print(stock[:,:,1])

[[20 25]
 [30 35]]


In [21]:
# 전체 재고 합계
print(np.sum(stock))

330


In [22]:
# 상품별 총 재고

# print(np.sum(stock[0]), np.sum(stock[1]))
print(stock.sum(axis=0))

[[30 50 70]
 [40 60 80]]


In [23]:
students = np.array([
    [90,80],
    [70,60],
    [100,95],
    [50,40],
    [85,90]
])

In [40]:
# 0번
# 2번
# 4번

print(students[[0,1,3], [1,0, 1]])

[80 70 40]


In [ ]:
a = np.arange(24).reshape(2,3,4)
a.shape

# [
#     [
#         [0,1,2,3],
#         [4,5,6,7],
#         [8,9,10,11],
#     ],
#     [
#         [12,13,14,15],
#         [16,17,18,19],
#         [20,21,22,23],
#     ]
# ]

(2, 3, 4)

In [43]:
# 첫 번째 층만 팬시 인덱싱으로 가져오세요.

print(a[[0]])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [44]:
# 첫 번째 층과 두 번째 층을 순서를 바꿔 가져오세요.

print(a[[1, 0]])

[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [49]:
# 모든 층에서 0번째 행과 2번째 행만 가져오세요.

print(a[:, [0,2], :])

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [20 21 22 23]]]


In [ ]:
# 모든 층에서 1번째 열만 가져오세요.

print(a[:, :, [1]])

[[[ 1]
  [ 5]
  [ 9]]

 [[13]
  [17]
  [21]]]


In [51]:
# 첫 번째 층에서 0번째 행과 2번째 행만 가져오세요.

print(a[[0], [0,2],:])

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [ ]:
# 첫 번째 층, 모든 행, 1번째 열만 가져오세요.

print(a[[0], :, [1]])

# [
#     [
#         [0,1,2,3],
#         [4,5,6,7],
#         [8,9,10,11],
#     ],
#     [
#         [12,13,14,15],
#         [16,17,18,19],
#         [20,21,22,23],
#     ]
# ]

[[1 5 9]]


In [ ]:
# print(a[[0,1], [2,0], [1,3]]) 결과 예측

[
    [
        [9,11],
        [1,3],
    ],
    [
        [21,23],
        [13,15],
    ]
]

In [5]:
a = "a234"

for i in a:
    try:
        int(i)
    except ValueError:
        print(False)


False
