In [ ]:
# NumPy 설치하기
!uv add numpy

In [1]:
import numpy as np

In [2]:
import numpy as np
print(np.__version__)

2.5.1


In [3]:
!uv  pip list | findstr numpy  

numpy                   2.5.1


In [4]:
# python을 이용한 계산
%time sum(range(1000000))

CPU times: total: 31.2 ms
Wall time: 22 ms


499999500000

In [5]:
# numpy을 이용한 계산
%time np.sum(np.arange(1000000))

CPU times: total: 15.6 ms
Wall time: 15.6 ms


np.int64(499999500000)

In [6]:
import numpy as np

# 2행 3열의 수치형 2차원 배열 정의
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("배열의 차원:", arr.ndim, np.ndim(arr))   # 출력: 2
print("배열의 형태:", arr.shape, np.shape(arr))  # 출력: (2, 3)
print("원소 총 개수:", arr.size, np.size(arr))  # 출력: 6
print("데이터 타입:", arr.dtype)  # 출력: int64

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입:", float_arr.dtype)  # 출력: float64


배열의 차원: 2 2
배열의 형태: (2, 3) (2, 3)
원소 총 개수: 6 6
데이터 타입: int64
변경된 타입: float64


In [7]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))            # <class 'numpy.ndarray'>
print(a.dtype)            # int64 : 정수 64bit => 8byte

<class 'numpy.ndarray'>
int64


In [8]:
import numpy as np

int64_a = np.array([1, 2, 3])
print(int64_a.dtype )
float32_b = int64_a.astype(np.float32)
print(float32_b )                 # array([1., 2., 3.])
print(float32_b .dtype)           # dtype('float32')

int64
[1. 2. 3.]
float32


In [9]:
a = np.zeros(3)
print(a)          # [0. 0. 0.]

[0. 0. 0.]


In [10]:
a = np.zeros((2,3))
print(a)          #[[0. 0. 0.][0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
a = np.ones(3)
print(a)             # [1. 1. 1.]

[1. 1. 1.]


In [12]:
a = np.ones((2,3))
print(a)             # [[1. 1. 1.][1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

b = np.ones_like(a) # a배열의 shape을 복사한다.
print(b)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


In [14]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.zeros_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.empty_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
a = [[1,2,3]]
print(type(a))           # list

b = a.copy()
print(id(a))              # 133162358428608
print(id(b))              # 133162358989568

print(a is b)             # False
print(a == b)             # True 

b[0][0] = 10
print(a[0])               # [10, 2, 3]
print(b[0])               # [10, 2, 3]

<class 'list'>
2052098083392
2052098082240
False
True
[10, 2, 3]
[10, 2, 3]


In [ ]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14]
])


print(arr[[1,2]])     # [[3, 4,5], [6, 7, 8]]

print(arr[[-1, -2]]) 

[[3 4 5]
 [6 7 8]]
[[12 13 14]
 [ 9 10 11]]


In [19]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [20]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [21]:
b = a[:, [1], :]
b.shape

(2, 1, 4)

In [23]:
a[[1]]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
b = a[[1],:, :]
b.shape

(1, 3, 4)

In [24]:
a[:,:,[1]]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [25]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [26]:
np.set_printoptions(edgeitems=6)

np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999], shape=(10000,))

In [28]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}') 
print(f' {arr is dap}')     

[1 2 3 4]
메모리 공유 확인:: False
 False


In [30]:
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d ,arr_2d)}') 
print(arr_1d is arr_2d)

메모리 공유 확인:: True
False


In [36]:
a = np.arange(12).reshape(3,4)
print(a)
x, y = np.split(a, 2, axis = 1)
print(x)
print(y)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [34]:
c = np.concatenate((x, y), axis=0)
print(c.shape)
print(c)

(6, 2)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]


In [35]:
c = np.concatenate((x, y), axis=1)
print(c.shape)
print(c)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [39]:
arr = np.array([1, 2, 3]) # shape: (3,)

# 행 방향(axis 0) 확장 -> shape: (1, 3)
row_vec = arr[np.newaxis, :]
row_vec

array([[1, 2, 3]])